# Generated by Django 4.1.3 on 2022-11-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pairs', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_pairs_temp', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_price', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_5m', models.FloatField(blank=True, null=True)),
                ('change_15m', models.FloatField(blank=True, null=True)),
                ('change_30m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Huobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pairs', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_pairs_temp', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_price', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_5m', models.FloatField(blank=True, null=True)),
                ('change_15m', models.FloatField(blank=True, null=True)),
                ('change_30m', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OKX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pairs', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_pairs_temp', models.CharField(blank=True, max_length=255, null=True)),
                ('coin_price', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_5m', models.FloatField(blank=True, null=True)),
                ('change_15m', models.FloatField(blank=True, null=True)),
                ('change_30m', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
