# Generated by Django 4.1.3 on 2022-12-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_chain_huobi_okx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pairs', models.CharField(blank=True, max_length=255, null=True)),
                ('binance', models.FloatField(blank=True, null=True)),
                ('okx', models.FloatField(blank=True, null=True)),
                ('huobi', models.FloatField(blank=True, null=True)),
                ('chain', models.FloatField(blank=True, null=True)),
                ('pricediff', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
