# Generated by Django 4.1.3 on 2022-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharinPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_pairs', models.CharField(max_length=255)),
                ('chain_id', models.CharField(max_length=255)),
                ('dex_id', models.CharField(max_length=255)),
                ('pair_address', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
    ]
