# Generated by Django 4.1.3 on 2022-12-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_charinpairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='charinpairs',
            name='labels',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charinpairs',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charinpairs',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='charinpairs',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
